### ISSUE TITLE
Broken Endpoint or Misleading documentation

### ISSUE THREAD

**Issue by maisans-maid** [Tamako-Tech/tamako.js#1]
I've tried fiddling with this api wrapper and turns out that the image method is always returning an unhandled promise rejection and with the error not being caught by the library itself (assuming it should since it has an error event is being emitted).

Ive used all the available categories listed in the README (documentation) and none of them work, tried using uppercase and lowercase but does not work aswell. I tried manually inputting the address on my browser and i found out that i was getting a 404 error.

![image](https://user-images.githubusercontent.com/56829176/103427220-7a423a80-4bfa-11eb-8a88-1f63845b5691.png)

PS. Other method works just fine

Thought i'd let you know since it's a great API

**Comment by BearTS** [comment]
aaa yes, if you look at the recent commits in the repo, you will see that it had been deprecated, its my bad that i didnt pushed the release to the npm database. 
Thanks for letting me know, i will push it tomorrow 👍

**Comment by BearTS** [comment]
New Package pushed.
