### ISSUE TITLE
chat endpoint always returs status 200

### ISSUE THREAD

**Issue by maisans-maid** [Tamako-Tech/tamako.js#3]
The chatbot endpoint always returns status 200, rendering [src/tamakoapi.js#L50](https://github.com/BearTS/tamako-api/blob/main/src/tamakoapi.js#L50) useless.

```js
const fetch = require("node-fetch")

fetch('http://api.tamako.tech/api/chat?'
+'username=undefined&appid=undefined&appsecret=undefined'
+'&message=undefined&name=undefined&user=undefined'
+'&gender=undefined').then(res => console.log(res.status))
// Logs 200

fetch('http://api.tamako.tech/api/chat?').then(res => console.log(res.status))
// Logs 200
```

Tested on runkit with Node vesion 15.x.x

P.S. This is really not a problem in the library, thought i'd just point out since it doesn't coincide with the behavior of the API.
In this case, the api should return an unauthorized access error (401).

**Comment by maisans-maid** [comment]
Should point out that the other endpoint correctly returns the status
```js
const fetch = require("node-fetch")

fetch('http://api.tamako.tech/api/pokemon?').then(res => console.log(res.status))
// logs 404
```

**Comment by BearTS** [comment]
Hmm i think i know the reason
i will check this soon
Thanks for notifying about it

**Comment by BearTS** [comment]
Fixed it
